/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package compiler;

import compiler.Lexer.Lexer;
import compiler.Lexer.Symbol;
import compiler.Lexer.TokenType;

import java.io.StringReader;

public class Compiler {
    public static void main(String[] args) {
        String testInput = "STRING name = \"Hello World\"; println(\"Hi\\nthere\");";
        Lexer lexer = new Lexer(new StringReader(testInput));

        Symbol symbol;
        while ((symbol = lexer.getNextSymbol()).getType() != TokenType.EOF) {
            System.out.println(symbol);
        }
    }
}
